NODE_DC = 0
NODE_SWITCH = 1
RESOURCE_TYPE = ["mem", "cpu", "ram"]
TIMESTEP = 0.1

LATENT_DIM = 16
MAX_DCS = 60
VGAE_DIR = "models/vgae_pretrained"
PLACER_DIR = "models/placer"
VGAE_WEIGHTS_FILE = "vgae_weights.npy"
PLACER_WEIGHTS_FILE = "placer_dqn_weights.npy"
PLACER_WEIGHT_NET_FILE = "placer_weight_net_weights.npy"

DEFAULT_VGAE_EPOCHS = 200
DEFAULT_PLACER_EPISODES = 500
DEFAULT_REQUEST_PCT = 0

DRL_PENALTY_DROP = 5.0
DRL_R_BASE_LL = 5.0
DRL_BATCH_SIZE = 64
DRL_TARGET_SYNC = 100
DRL_VGAE_TRAIN_FREQ = 500
DRL_VGAE_EPOCHS = 3
DRL_MAX_GRAPH_CACHE = 500

EPSILON_MAX = 1.0
EPSILON_MIN = 0.05
EPSILON_WARMUP = 0.05

DRL_LL_ALPHA = 2.0
DRL_LL_BETA = 0.1

ROUTING_DELAY_WEIGHT    = 0.4
ROUTING_BW_WEIGHT       = 0.3
ROUTING_PRESSURE_WEIGHT = 0.2
ROUTING_HOP_WEIGHT      = 0.1

HRL_VGAE_FINETUNE_LR    = 1e-5
HRL_VGAE_FINETUNE_FREQ  = 500
HRL_VGAE_FINETUNE_EPOCHS = 1
HRL_VGAE_ONLINE         = False

ADMISSION_WINDOW_SIZE    = 10
ADMISSION_HIDDEN_DIM     = 128
ADMISSION_LR             = 3e-4
ADMISSION_PPO_EPOCHS     = 4
ADMISSION_CLIP_EPS       = 0.2
ADMISSION_GAMMA          = 0.99
ADMISSION_LAM            = 0.95
ADMISSION_ENTROPY_COEF   = 0.01
ADMISSION_VALUE_COEF     = 0.5
ADMISSION_START_FRAC     = 0.25

# Reject only when P(reject) >= this threshold; otherwise default accept.
ADMISSION_REJECT_THRESHOLD = 0.65

# Static R2C floor: always reject if R2C < floor (0.0 = disabled).
ADMISSION_R2C_FLOOR      = 0.0

# Pure-accept warmup episodes after admission activates.
ADMISSION_WARMUP_EPISODES = 5

REVENUE_WEIGHT_NODE     = 1.0
REVENUE_WEIGHT_LINK     = 1.0

PLACER_HIDDEN_DIM       = 256
PLACER_LR               = 3e-4