NODE_DC = 0
NODE_SWITCH = 1
RESOURCE_TYPE = ["mem", "cpu", "ram"]
TIMESTEP = 0.1

LATENT_DIM = 8
MAX_DCS = 60
VGAE_DIR = "models/vgae_pretrained"
PLACER_DIR = "models/placer"
VGAE_WEIGHTS_FILE = "vgae_weights.npy"
PLACER_WEIGHTS_FILE = "placer_dqn_weights.npy"
PLACER_WEIGHT_NET_FILE = "placer_weight_net_weights.npy"

DEFAULT_VGAE_EPOCHS = 60
DEFAULT_PLACER_EPISODES = 60
DEFAULT_REQUEST_PCT = 0

ROUTING_BW_WEIGHT = 0.3
ROUTING_PRESSURE_WEIGHT = 0.5

HRL_BASE_REWARD = 1.0
HRL_PENALTY_DROP = 0.5
HRL_R_BASE_LL = 1.0
HRL_BATCH_SIZE = 32
HRL_TARGET_SYNC = 100
HRL_VGAE_TRAIN_FREQ = 200
HRL_VGAE_EPOCHS = 3
HRL_MAX_PATH_CACHE = 500
HRL_MAX_ROUTING_CACHE = 20000
HRL_MAX_GRAPH_CACHE = 500

EPSILON_MAX = 0.9
EPSILON_MIN = 0.1
EPSILON_WARMUP = 0.1

HRL_LL_ALPHA = 0.5
HRL_LL_BETA = 1.0
HRL_LL_GAMMA_POT = 0.3